name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci  

      - name: 🧪 Run tests
        run: npm test 

      - name: 💄 Run Code Style Checks (optional)
        run: npm run check-style 

